language: node_js
node_js:
  - "0.12"
  - "0.10"
before_install:
  - sudo apt-get install libgif-dev
  - npm install -g gulp
install: npm install
before_script: gulp build
after_success: ./node_modules/.bin/coveralls --verbose < coverage/lcov.info