language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
addons:
  apt:
    packages:
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
    - g++
install: npm install